- name: Install postfix
  apt:
    name: "{{ ['postfix'] }}"
    state: present

- name: Create ssl directory
  file: path={{ item.path }} owner={{ item.owner }} group={{ item.group }} mode={{ item.mode }} state=directory
  with_items:
    - { path: '/etc/postfix/ssl', owner: 'root', group: 'root', mode: '0755' }

- name: Setup configuration file for postfix
  copy: owner={{ item.owner }} group={{ item.group }} mode={{ item.mode }} src={{ item.src }} dest={{ item.dest }}
  with_items: 
    - { src: 'master.cf', dest: '/etc/postfix/master.cf', owner: 'root', group: 'root', mode: '0644' }
    - { src: 'main.cf', dest: '/etc/postfix/main.cf', owner: 'root', group: 'root', mode: '0644' }
    - { src: 'canonical.recipient', dest: '/etc/postfix/canonical.recipient', owner: 'root', group: 'root', mode: '0644' }
    - { src: 'mysql-virtual_domains.cf', dest: '/etc/postfix/', owner: 'root', group: 'root', mode: '0644' }
    - { src: 'mysql-virtual_email2email.cf', dest: '/etc/postfix/', owner: 'root', group: 'root', mode: '0644' }
    - { src: 'mysql-virtual_forwardings.cf', dest: '/etc/postfix/', owner: 'root', group: 'root', mode: '0644' }
    - { src: 'mysql-virtual_mailboxes.cf', dest: '/etc/postfix/', owner: 'root', group: 'root', mode: '0644' }
    - { src: 'mysql-virtual_mailbox_limit_maps.cf', dest: '/etc/postfix/', owner: 'root', group: 'root', mode: '0644' }
    - { src: 'mysql-virtual_transports.cf', dest: '/etc/postfix/', owner: 'root', group: 'root', mode: '0644' }
    - { src: 'mailname', dest: '/etc/mailname', owner: 'root', group: 'root', mode: '0644' }
  register: postfix_conf

  # TODO: take care of the certificates

- name: Reload postfix config
  shell: postmap /etc/postfix/canonical.recipient
  when: postfix_conf.changed

- name: Restart postfix
  systemd: state=restarted enabled=yes name=postfix
  when: postfix_conf.changed


