---
- name: Services dirs
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: "0700"
  loop:
    - "{{ svc_dir }}"
    - "{{ svc_scripts_dir }}"
    - "{{ svc_data_dir }}"

- name: Log dirs
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: "0700"
  loop:
    - "{{ traefik_log_dir }}"
    - "{{ scripts_log_dir }}"

- name: Scripts
  template:
    src: "{{ item }}"
    dest: "{{ svc_scripts_dir }}/"
    owner: root
    group: root
    mode: "0700"
  loop:
    - ovh_dns_update.sh

- name: Docker compose files
  template:
    src: "{{ item }}"
    dest: "{{ svc_dir }}/"
    owner: root
    group: root
    mode: "0400"
  loop:
    - docker-compose.yaml
    - traefik.yaml
    - radicale_config
  notify:
    - jibux_svc service state

- name: Logrotates
  template:
    src: "jibux_svc-logrotate"
    dest: "/etc/logrotate.d/jibux_svc"
    owner: root
    group: root
    mode: "0444"

- name: mega-cmd service install
  template:
    src: mega-cmd.service
    dest: /etc/systemd/system/mega-cmd.service
    mode: "0444"
  notify:
    - Systemd daemon reload

- name: Docker compose service install
  template:
    src: jibux_svc.service.j2
    dest: /etc/systemd/system/jibux_svc.service
    mode: "0444"
  notify:
    - Systemd daemon reload
    - jibux_svc service state
