---
- include_tasks:
    file: softs.yml
    apply:
      tags:
        - softs
  tags:
    - softs

- include_tasks:
    file: compose.yml
    apply:
      tags:
        - compose
  tags:
    - compose

- include_tasks:
    file: mega.yml
    apply:
      tags:
        - mega
  tags:
    - mega

- include_tasks:
    file: ovh_cred.yml
    apply:
      tags:
        - ovh_cred
  tags:
    - ovh_cred

- name: jibux_svc service enabled/disabled
  systemd:
    name: jibux_svc
    enabled: "{{ svc_enabled | bool }}"
  tags:
    - compose
