---
- include_tasks:
    file: softs.yml
    apply:
      tags:
        - softs
  tags:
    - softs

- include_tasks:
    file: compose.yml
    apply:
      tags:
        - compose
  tags:
    - compose
    - compose_files

- name: Launch mega-cli.py
  command: "{{ mega_cli_exec }} -v -w jibux_svc_data_traefik,jibux_svc_data_secrets"
  register: mega_cli_output

- debug:
    msg: "{{ mega_cli_output }}"

- include_tasks:
    file: ovh_cred.yml
    apply:
      tags:
        - ovh_cred
  when: setup_credentials | d(false) | bool
  tags:
    - ovh_cred

- name: jibux_svc service enabled/disabled
  systemd:
    name: jibux_svc
    enabled: "{{ svc_enabled | bool }}"
  tags:
    - compose
