---
- name: Login status
  command: mega-session
  register: mega_session
  check_mode: false
  ignore_errors: true

- assert:
    that: not mega_session.failed
    fail_msg: You must connect with MEGA account with '{{ ansible_user }}' user
    success_msg: Connected with MEGA account
  ignore_errors: true

- when: mega_session.failed
  block:
    - pause:
        prompt: "MEGA account email"
      register: email
    - pause:
        prompt: "MEGA account password"
        echo: false
      register: password
    - pause:
        prompt: "MEGA totp code"
        echo: false
      register: totp_code

    - name: Login to MEGA
      command: mega-login --auth-code={{ totp_code.user_input }} {{ email.user_input }} {{ password.user_input }}
      check_mode: false

- name: List MEGA exclude
  command: mega-exclude
  register: mega_exclude
  check_mode: false

- name: Remove hidden files from MEGA exclude
  command: mega-exclude -d '.*'
  when: "'.*' in mega_exclude.stdout_lines"

- name: List MEGA sync dirs
  command: "mega-sync --col-separator=: --output-cols=LOCALPATH,REMOTEPATH"
  register: mega_sync
  check_mode: false

- when: svc_data_dir + ':' + mega_data_path not in mega_sync.stdout_lines
  block:
    - name: Mkdir MEGA data path
      command: mega-mkdir -p "{{ mega_data_path }}"
      ignore_errors: true

    - name: Sync data folder
      command: mega-sync "{{ svc_data_dir }}/" "{{ mega_data_path }}/"
