---
- name: Add mega apt key
  apt_key:
    url: https://mega.nz/keys/MEGA_signing.key
    keyring: /usr/share/keyrings/meganz-archive-keyring.gpg
    state: present

- name: Add mega repo
  apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/meganz-archive-keyring.gpg] https://mega.nz/linux/repo/xUbuntu_{{ ansible_distribution_version }}/ ./"
    filename: megasync.list
    state: present

- name: Add docker apt key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    keyring: /etc/apt/keyrings/docker.gpg
    state: present

- name: Add docker repo
  apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    filename: docker
    state: present

- name: Install softwares
  apt:
    update-cache: true
    name:
      - docker
      - megacmd
      - jq
      - net-tools
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: latest




