---
- name: Install rsnapshot
  apt:
    name: rsnapshot
    state: present

- name: Setup rsnapshot config
  template:
    src: rsnapshot.conf.j2
    dest: /etc/rsnapshot.conf

- name: Create backup script dir
  file:
    path: /home/data/scripts/backup/
    state: directory

- name: Copy backup script
  copy:
    src: backup.sh
    dest: /home/data/scripts/backup/backup.sh
