---
ansible_connection: local
svc_enabled: true
svc_interface: wlo1
svc_router_whitelist:
  - mac: f4:42:8f:11:55:a2
    description: Samsung Galaxy A3 connection sharing
  - mac: f4:ca:e5:42:6d:e6
    description: Home
  - mac: 24:95:04:8f:37:c0
    description: Mayumba
  - mac: b8:26:6c:ce:5d:e2
    description: Bvd Jean-Mermoz
