---
- name: Gather package facts
  package_facts:
    manager: apt

- when: "'snapd' in ansible_facts.packages"
  block:
    - name: List snap packages
      shell:
        cmd: snap list --color=never --unicode=never | tail -n +2 | grep -v snapd | awk '{print $1}'
      register: snap_list

    - name: Remove snap packages
      community.general.snap:
        name: "{{ snap_list.stdout_lines }}"
        state: absent

    - name: Remove snap packages (snapd)
      community.general.snap:
        name: snapd
        state: absent

- name: Remove snapd
  apt:
    name: snapd
    state: absent
    purge: true

- name: Remove snap cache
  file:
    path: /var/cache/snapd/
    state: absent

- name: Blacklist snapd
  copy:
    src: nosnap.pref
    dest: /etc/apt/preferences.d/nosnap.pref
    owner: root
    group: root
    mode: 444
