---
- name: Add group to user www-data
  user: name=www-data groups='jb_dedi_web'

- name: Install webserver programs
  apt:
    name: "{{ ['apache2', 'php7.3-fpm', 'sslh', 'openvpn', 'iptables-persistent', 'letsencrypt', 'fail2ban', 'bind9', 'mariadb-server-10.1'] }}"
    state: present

- name: Install Python modules
  apt:
    name: "{{ ['python3-bottle', 'python3-simplejson'] }}"
    state: present

- name: Install apache2 modules
  apt:
    name: "{{ ['libapache2-mod-wsgi-py3'] }}"
    state: present

- name: Enable apache2 modules
  apache2_module: name={{ item }} state=present ignore_configcheck=yes
  loop: "{{ ['headers', 'rewrite', 'wsgi', 'ssl', 'proxy', 'proxy_http', 'proxy_fcgi', 'http2'] }}"

- name: Install php modules
  apt:
    name: "{{ ['php7.3-mysql', 'php-apcu', 'php7.3-intl', 'php7.3-xml', 'php7.3-gd', 'php7.3-curl', 'php7.3-zip', 'php7.3-mbstring', 'php7.3-ldap', 'php7.3-imap', 'php7.3-sqlite3', 'php7.3-bz2'] }}"
    state: present
  register: php_modules_insalled

- name: Enable php modules
  shell: phpenmod {{ item }}
  with_items:
    - mysql
    - apcu
    - json
    - intl
    - simplexml
    - xmlreader
    - xmlwriter
    - xml
    - gd
    - curl
    - zip
    - mbstring
    - ldap
    - imap
    - sqlite3
    - bz2
  when: php_modules_insalled.changed

# Set ip forwarding on in /proc and in the sysctl file and reload if necessary
- sysctl:
    name: net.ipv4.ip_forward
    value: "1"
    sysctl_set: true
    state: present
    reload: true

- name: Setup configuration files
  copy: owner={{ item.owner }} group={{ item.group }} mode={{ item.mode }} src={{ item.src }} dest={{ item.dest }}
  with_items:
    - { src: 'apache2.conf', dest: '/etc/apache2/apache2.conf', owner: 'root', group: 'root', mode: '0644' }
    - { src: 'ports.conf', dest: '/etc/apache2/ports.conf', owner: 'root', group: 'root', mode: '0644' }
    - { src: '000-default.conf', dest: '/etc/apache2/sites-available/000-default.conf', owner: 'root', group: 'root', mode: '0644' }
    - { src: 'jibux.info.conf', dest: '/etc/apache2/sites-available/jibux.info.conf', owner: 'root', group: 'root', mode: '0644' }
    - { src: 'security.conf', dest: '/etc/apache2/conf-available/security.conf', owner: 'root', group: 'root', mode: '0644' }
    - { src: 'jb_dedi_web.conf', dest: '/etc/php/7.3/fpm/pool.d/jb_dedi_web.conf', owner: 'root', group: 'root', mode: '0644' }
    - { src: 'php-fpm.conf', dest: '/etc/php/7.3/fpm/php-fpm.conf', owner: 'root', group: 'root', mode: '0644' }
    - { src: 'php.ini', dest: '/etc/php/7.3/fpm/php.ini', owner: 'root', group: 'root', mode: '0644' }
    - { src: 'sslh', dest: '/etc/default/sslh', owner: 'root', group: 'root', mode: '0644' }
    - { src: 'my.cnf', dest: '/etc/mysql/my.cnf', owner: 'root', group: 'root', mode: '0644' }
    - { src: 'rules.v4', dest: '/etc/iptables/rules.v4', owner: 'root', group: 'root', mode: '0644' }
    - { src: 'rules.v6', dest: '/etc/iptables/rules.v6', owner: 'root', group: 'root', mode: '0644' }
    - { src: 'f2b_jail.local', dest: '/etc/fail2ban/jail.local', owner: 'root', group: 'root', mode: '0640' }
    - { src: 'sudoers', dest: '/etc/sudoers', owner: 'root', group: 'root', mode: '0440' }
    - { src: 'sshd_config', dest: '/etc/ssh/sshd_config', owner: 'root', group: 'root', mode: '0644' }
    - { src: 'interfaces', dest: '/etc/network/interfaces', owner: 'root', group: 'root', mode: '0644' }
  register: config_webserver

- name: Untar debian.cnf files from backup
  shell: cd / && tar --occurrence -xzf /mnt/backup/last_backup.tgz etc/mysql/debian.cnf
  when: first_install is defined and first_install == "yes"

- name: Setup logrotate files
  copy: owner={{ item.owner }} group={{ item.group }} mode={{ item.mode }} src={{ item.src }} dest={{ item.dest }}
  with_items:
    - { src: 'apache2-private', dest: '/etc/logrotate.d/apache2-private', owner: 'root', group: 'root', mode: '0644' }
    - { src: 'renew_lets_encrypt', dest: '/etc/logrotate.d/renew_lets_encrypt', owner: 'root', group: 'root', mode: '0644' }
    - { src: 'openvpn', dest: '/etc/logrotate.d/openvpn', owner: 'root', group: 'root', mode: '0644' }

- name: Disable cron in /etc/cron.d/certbot
  replace:
    path: /etc/cron.d/certbot
    regexp: '(^0.*)'
    replace: '#\1'

- name: Stat /etc/php/7.3/fpm/pool.d/www.conf
  stat: path=/etc/php/7.3/fpm/pool.d/www.conf
  register: www_conf_stat

- name: Move www.conf to www.conf.dist
  command: mv /etc/php/7.3/fpm/pool.d/www.conf /etc/php/7.3/fpm/pool.d/www.conf.dist
  when: www_conf_stat.stat.exists

- name: Enable site for apache2
  shell: a2ensite {{ item }}
  with_items:
    - jibux.info.conf
    - 000-default.conf
  when: config_webserver.changed

- name: Stop fail2ban services
  systemd: state=stopped name=fail2ban
  when: config_webserver.changed

- name: Execute iptables
  shell: /home/data/scripts/iptables/iptables.sh load
  when: config_webserver.changed

- name: Restart services (1/3)
  systemd: state=restarted enabled=yes name={{ item }}
  with_items:
    - fail2ban
    - ssh
    - php7.3-fpm
    - mariadb
  when: config_webserver.changed

- name: Restart services - stop (2/3)
  systemd: state=stopped enabled=yes name={{ item }}
  with_items:
    - openvpn
    - apache2
    - sslh
  when: config_webserver.changed

- name: Restart services - start (3/3)
  systemd: state=started name={{ item }}
  with_items:
    - openvpn
    - apache2
    - sslh
  when: config_webserver.changed
