- name: Create directories
  file: path={{ item.path }} owner={{ item.owner }} group={{ item.group }} mode={{ item.mode }} state=directory
  with_items:
    - { path: '/home/www', owner: 'root', group: 'root', mode: '0751' }
    - { path: '/etc/iptables', owner: 'root', group: 'root', mode: '0755' }

- name: Create groups
  group: name={{ item.name }} gid={{ item.gid }} state=present
  with_items:
    - { name: 'www', gid: 6000 }
    - { name: 'sftp', gid: 6001 }
    - { name: 'jbh', gid: 1000 }
    - { name: 'jb_dedi_web', gid: 2000 }

- name: Create users
  user: name={{ item.name }} uid={{ item.uid }} group={{ item.group }} groups={{ item.groups }} home={{ item.home }} shell={{ item.shell }} password={{ item.password }}
  with_items:
    - { name: 'jbh', uid: 1000, group: 'jbh', home: '/home/jbh', groups: 'sudo', shell: '/bin/bash', password: '$6$QEmOr9SX$fXxwROHbfCfJs/zEVmzACiqPQxVtDA/FbCN3utTxrr/ZWx7FfC2WIQPeTwK7rQym2t0qQjk2NCIXSmn4X3G9d0' }
    - { name: 'jb_dedi_web', uid: 2000, group: 'jb_dedi_web', home: '/home/www/jb_dedi_web', groups: 'www, sftp', shell: '/bin/bash', password: '!' }

- name: Install tools
  apt:
    name: "{{ ['vim', 'autofs', 'mlocate', 'tcpdump', 'apt-file', 'unattended-upgrades', 'sysstat', 'git', 'lvm2', 'smartmontools', 'hdparm'] }}"
    state: present
  register: tools_installed

- name: Run apt-file update
  shell: apt-file update
  when: tools_installed.changed

- name: Set timezone to Europe/Paris
  timezone:
    name: Europe/Paris
  register: timezone_setup

- name: Restart crond
  systemd: state=restarted name=cron
  when: timezone_setup.changed

- name: Create directories
  file: path={{ item.path }} owner={{ item.owner }} group={{ item.group }} mode={{ item.mode }} state=directory
  with_items:
#    - { path: '/mnt/backup', owner: 'root', group: 'root', mode: '0750' }
    - { path: '/var/log/backup', owner: 'root', group: 'root', mode: '0755' }

- name: Setup misc configuration files
  copy: owner={{ item.owner }} group={{ item.group }} mode={{ item.mode }} src={{ item.src }} dest={{ item.dest }}
  with_items: 
    - { src: 'hosts', dest: '/etc/hosts', owner: 'root', group: 'root', mode: '0644' }
    - { src: 'vimrc', dest: '/etc/vim/vimrc', owner: 'root', group: 'root', mode: '0644' }
    - { src: 'root_bashrc', dest: '/root/.bashrc', owner: 'root', group: 'root', mode: '0644' }
    - { src: '.selected_editor', dest: '/root/.selected_editor', owner: 'root', group: 'root', mode: '0644' }
    - { src: '50unattended-upgrades', dest: '/etc/apt/apt.conf.d/50unattended-upgrades', owner: 'root', group: 'root', mode: '0644' }
    - { src: 'hdparm.conf', dest: '/etc/hdparm.conf', owner: 'root', group: 'root', mode: '0644' }
  register: config_misc

- name: Disable and stop services
  systemd: state=stopped enabled=no name={{ item }}
  with_items:
    - smartmontools
    - smartd

- name: Restart misc services
  systemd: state=restarted enabled=yes name={{ item }}
  with_items:
    - unattended-upgrades
  when: config_misc.changed

- name: Setup configuration file for autofs
  copy: owner={{ item.owner }} group={{ item.group }} mode={{ item.mode }} src={{ item.src }} dest={{ item.dest }}
  with_items: 
    - { src: 'auto.mnt', dest: '/etc/auto.mnt', owner: 'root', group: 'root', mode: '0644' }
    - { src: 'auto.master', dest: '/etc/auto.master', owner: 'root', group: 'root', mode: '0644' }
  register: autofs_conf

- name: Restart autofs
  systemd: state=restarted enabled=yes name=autofs
  when: autofs_conf.changed

- name: Setup cron
  copy: owner={{ item.owner }} group={{ item.group }} mode={{ item.mode }} src={{ item.src }} dest={{ item.dest }}
  with_items: 
    - { src: 'cron_root', dest: '/var/spool/cron/crontabs/root', owner: 'root', group: 'crontab', mode: '600' }

- name: Untar home from backup
  shell: cd / && tar -xzf /mnt/backup/last_backup.tgz home/
  when: first_install is defined and first_install == "yes"


