---
svc_host: svc.jibux.info
dav_sync_host: dav.jibux.info
svc_dir: /opt/jibux_svc
svc_data_dir: "{{ svc_dir }}/data"
svc_scripts_dir: "{{ svc_dir }}/scripts"
mega_data_path: /dev_and_scripts/jibux_svc_data
ovh_dyndns_cred_path: "{{ svc_data_dir }}/secrets/ovh_dyndns"
log_dir: /var/log/jibux_svc
traefik_log_dir: "{{ log_dir }}/traefik"
scripts_log_dir: "{{ log_dir }}/scripts"
svc_enabled: false
compose_version: 3.7
radicale_version: 3.1.8.1
traefik_version: 2.9
radicale_port: 5231
